[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "0x5c6370"
blue = "0x61afef"
cyan = "0x2bbac5"
green = "0x98c379"
magenta = "0xc678dd"
# orange = "0xd19a66"
red = "0xef596f"
white = "0xffffff"
yellow = "0xd19a66"

[colors.normal]
black = "0x1e1e1e"
blue = "0x61afef"
cyan = "0x2bbac5"
green = "0x98c379"
magenta = "0xc678dd"
# orange = "0xd19a66"
red = "0xef5950"
white = "0xabb2bf"
yellow = "0xd19a66"

[colors.primary]
background = "0x1e1e1e"
foreground = "0xffffff"

[font]
size = 12

[font.bold]
family = "Hack Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Hack Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Hack Nerd Font"
style = "Italic"

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true

[shell]
program = "/bin/fish"

[window]
decorations = "none"
opacity = 0.98

[window.dimensions]
columns = 90
lines = 28

[window.padding]
x = 20
y = 20
