add_newline = false

[line_break]
disabled = true

[package]
disabled = true

[cmd_duration]
disabled = true

[battery]
disabled = true

[character]
vicmd_symbol = '[NORMAL](bold red)'
success_symbol = '[❯](bold red)'
error_symbol = '[](bold red)'

[directory]
style = 'bold white'
read_only = ' '

[git_branch]
style = 'bold blue'

[rust]
disabled = true

[python]
disabled = true

[cmake]
disabled = true

# [c]
# disabled = true

[java]
disabled = true

[nodejs]
disabled = true
