add_newline = false

[line_break]
disabled = true

[package]
disabled = true

[cmd_duration]
disabled = true

[battery]
disabled = true

[character]
vicmd_symbol = '[-](bold red)'
success_symbol = '[❯](bold red)'
error_symbol = '[x](bold red)'

[directory]
style = 'bold white'
read_only = 'r'

[git_branch]
style = 'bold blue'

[rust]
disabled = true

[python]
disabled = true

[cmake]
disabled = true

[nodejs]
disabled = true