theme = "onedark"

[editor]
line-number = "relative"
mouse = true
bufferline = "multiple"
completion-trigger-len = 1
color-modes = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = true

[editor.soft-wrap]
enable = true
max-wrap = 25 # increase value to reduce forced mid-word wrapping

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
C-7 = ["toggle_comments"]
H = ["move_char_left", "move_char_left", "move_char_left", "move_char_left", "move_char_left"]
J = ["move_line_down", "move_line_down", "move_line_down", "move_line_down", "move_line_down"]
K = ["move_line_up", "move_line_up", "move_line_up", "move_line_up", "move_line_up"]
L = ["move_char_right", "move_char_right", "move_char_right", "move_char_right", "move_char_right"]

[keys.normal.space]
w = ":write"
q = ":quit"

[keys.insert]
C-h = "move_char_left"
C-j = "move_line_down"
C-k = "move_line_up"
C-l = "move_char_right"
C-w = "move_next_word_start"
C-b = "move_prev_word_start"
C-e = "move_next_word_end"
