theme = "onedark"

[editor]
line-number = "relative"
mouse = true
bufferline = "never"
completion-trigger-len = 1
color-modes = true
auto-info = false
popup-border = "all"
rounded-corners = true
end-of-line-diagnostics = "hint"
completion-timeout = 5

[editor.statusline]
left = ["mode", "spinner", "file-name", "read-only-indicator", "file-modification-indicator"]
right = ["diagnostics", "file-encoding", "register", "position-percentage"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = true

[editor.soft-wrap]
enable = true
max-wrap = 25 # increase value to reduce forced mid-word wrapping

[editor.smart-tab]
enable = false

[editor.inline-diagnostics]
cursor-line = "warning"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
C-7 = ["toggle_comments"]
# C-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
# C-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
X = ["extend_line_up", "extend_to_line_bounds"]
C-h = ["jump_view_left"]
C-j = ["jump_view_down"]
C-k = ["jump_view_up"]
C-l = ["jump_view_right"]
D = "@xd"
Y = "@xy"

[keys.normal.space]
w = ":write"
q = ":quit"

[keys.insert]
C-h = "move_char_left"
C-j = "move_line_down"
C-k = "move_line_up"
C-l = "move_char_right"
C-w = "move_next_word_start"
C-b = "move_prev_word_start"
C-e = "move_next_word_end"
