[[language]]
name = "rust"
language-server = { command = "rustup", args = ["run", "stable", "rust-analyzer"] }
[language.config.check]
command = "clippy"

[[language]]
name = "cpp"
language-server = { command = "clangd", args=["--compile-commands-dir=compile_commands_directory"] }

[[language]]
name = "bash"
file-types = ["config", "sh", "conf"]
language-server = { command = "bash-language-server", args=["--stdio"] }
