# https://github.com/vlabo/cspell-lsp
[language-server.cspell]
command = "cspell-lsp"
args = ["--stdio"]

[language-server.typos]
command = "typos-lsp"

[[language]]
name = "rust"
language-servers = [ "rust-analyzer", "typos" ]

[language-server.rust-analyzer]
command = "rustup"
args = ["run", "stable", "rust-analyzer"]

[language-server.rust-analyzer.config.check]
command = "clippy"

[[language]]
name = "cpp"
language-servers = [ "clangd" ]

[language-server.clangd]
command = "clangd"
args = ["--compile-commands-dir=compile_commands_directory"]

[[language]]
name = "python"
language-servers = [ "pylsp", "typos" ]

[language-server.pylsp]
command = "pylsp"

[[language]]
name = "bash"
file-types = ["config", "sh", "conf"]
language-servers = [ "bash", "typos" ]

[language-server.bash]
command = "bash-language-server"
args = ["--stdio"]

[[language]]
name = "latex"
file-types = ["tex"]
language-servers = [ "texlab", "cspell" ]

[language-server.texlab]
command = "texlab"

[language-server.texlab.config.texlab.build]
onSave = true
args = ["-output-format=pdf", "--shell-escape"]

[language-server.texlab.config.texlab.chktex]
onEdit = true
