[[language]]
name = "rust"
language-servers = [ "rust-analyzer" ]

[language-server.rust-analyzer]
command = "rustup"
args = ["run", "stable", "rust-analyzer"]

[language-server.rust-analyzer.config.check]
command = "clippy"

[[language]]
name = "cpp"
language-servers = [ "clangd" ]

[language-server.clangd]
command = "clangd"
args = ["--compile-commands-dir=compile_commands_directory"]

[[language]]
name = "bash"
file-types = ["config", "sh", "conf"]
language-servers = [ "bash" ]

[language-server.bash]
command = "bash-language-server"
args = ["--stdio"]

[[language]]
name = "latex"
file-types = ["tex"]
language-servers = [ "texlab" ]

[language-server.texlab]
command = "texlab"

[language-server.texlab.config.texlab.build]
onSave = true

[language-server.texlab.config.texlab.chktex]
onEdit = true
